#!/usr/bin/env node
/* Generates web/sp-schemas.js from the vendored snapshot sp-system-spec/schemas/*.json.
   The vendored schemas are never edited; this bundle is a mechanical, byte-faithful embedding
   (parsed JSON), so browsers/Electron can validate without file access.
   Usage: node scripts/gen-schemas.js [--check] */
'use strict';
var fs = require('fs'), path = require('path');
var root = path.join(__dirname, '..');
var dir = path.join(root, 'sp-system-spec', 'schemas');
var out = path.join(root, 'web', 'sp-schemas.js');

function build() {
  var spec = fs.readFileSync(path.join(root, 'sp-system-spec', 'SPEC_HASH'), 'utf8').split('\n')[0].trim();
  var o = {};
  fs.readdirSync(dir).filter(function (f) { return /\.schema\.json$/.test(f); }).sort().forEach(function (f) {
    o[f] = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
  });
  return '/* GENERATED by scripts/gen-schemas.js from sp-system-spec/schemas — do not edit. */\n' +
    '(function (root, factory) {\n' +
    "  if (typeof module === 'object' && module.exports) module.exports = factory();\n" +
    '  else root.SPSchemas = factory();\n' +
    "})(typeof self !== 'undefined' ? self : this, function () {\n" +
    "  'use strict';\n" +
    '  return { specHash: ' + JSON.stringify(spec) + ', schemas: ' + JSON.stringify(o, null, 1) + ' };\n' +
    '});\n';
}
var text = build();
if (process.argv.indexOf('--check') >= 0) {
  var cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (cur !== text) { console.error('web/sp-schemas.js is out of date: run node scripts/gen-schemas.js'); process.exit(1); }
  console.log('sp-schemas.js ok');
} else { fs.writeFileSync(out, text); console.log('wrote', out); }
