/* GENERATED by scripts/gen-schemas.js from sp-system-spec/schemas — do not edit. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.SPSchemas = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return { specHash: "83f2954447d164842e9c0ade28253a0b9898997484b261a629de2275fe6d0225", schemas: {
 "analysis.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/analysis.schema.json",
  "title": "TrackUnderstanding (analysis/track.json)",
  "description": "LEARN-owned. DROP may ignore the whole file but must preserve it. Every inferred property is {raw, userOverride, confidence?}. Unknown properties are allowed everywhere.",
  "type": "object",
  "properties": {
   "analysisVersion": {
    "type": "integer",
    "minimum": 1
   },
   "producedBy": {
    "$ref": "common.schema.json#/$defs/producer"
   },
   "producedAt": {
    "$ref": "common.schema.json#/$defs/isoTime"
   },
   "audioSha256": {
    "$ref": "common.schema.json#/$defs/sha256",
    "description": "Hash of the audio this analysis describes. If the source changes, the analysis is stale (kept, but flagged)."
   },
   "tempo": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {bpm, beatOffsetSeconds, confidence, alternatives[]}"
   },
   "meter": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {beatsPerBar, confidence}"
   },
   "key": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {tonic, mode, confidence}"
   },
   "genre": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {status, primary, subgenre, candidates[{genre, confidence}]}; userOverride: {genre}"
   },
   "groove": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {swing, density, ...} (experimental measurements)"
   },
   "drums": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {events[], patterns[]}"
   },
   "bass": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {notes[], range}"
   },
   "structure": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {sections[{label,startSeconds,endSeconds,startBar,endBar}]}"
   },
   "phrases": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {phrases[]}"
   },
   "vocals": {
    "allOf": [
     {
      "$ref": "common.schema.json#/$defs/overridable"
     }
    ],
    "description": "raw: {regions[]}"
   },
   "chopCandidates": {
    "type": "array",
    "description": "SUGGESTIONS. Never shown as confirmed chops.",
    "items": {
     "type": "object",
     "properties": {
      "id": {
       "$ref": "common.schema.json#/$defs/stableId"
      },
      "kind": {
       "enum": [
        "drum-break",
        "vocal",
        "melodic-loop",
        "texture",
        "bass",
        "other"
       ]
      },
      "label": {
       "type": "string"
      },
      "startSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "endSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "confidence": {
       "$ref": "common.schema.json#/$defs/confidence"
      },
      "reason": {
       "type": "string"
      },
      "state": {
       "enum": [
        "suggested",
        "accepted",
        "dismissed"
       ],
       "default": "suggested"
      },
      "acceptedChopId": {
       "$ref": "common.schema.json#/$defs/stableId"
      }
     },
     "required": [
      "id",
      "kind",
      "startSeconds",
      "endSeconds"
     ],
     "additionalProperties": true
    }
   },
   "loopCandidates": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "id": {
       "$ref": "common.schema.json#/$defs/stableId"
      },
      "startSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "endSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "bars": {
       "type": "number"
      },
      "confidence": {
       "$ref": "common.schema.json#/$defs/confidence"
      },
      "loopability": {
       "$ref": "common.schema.json#/$defs/confidence"
      },
      "state": {
       "enum": [
        "suggested",
        "accepted",
        "dismissed"
       ]
      }
     },
     "required": [
      "id",
      "startSeconds",
      "endSeconds"
     ],
     "additionalProperties": true
    }
   }
  },
  "required": [
   "analysisVersion"
  ],
  "additionalProperties": true
 },
 "chops.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/chops.schema.json",
  "title": "Confirmed chops (project/chops.json)",
  "description": "Only chops a person confirmed (or that the app created on the person's request). Analysis suggestions live in analysis/track.json and are NOT chops until accepted.",
  "type": "object",
  "properties": {
   "schemaVersion": {
    "type": "integer",
    "minimum": 1
   },
   "chops": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "id": {
       "$ref": "common.schema.json#/$defs/stableId"
      },
      "name": {
       "type": "string"
      },
      "source": {
       "$ref": "common.schema.json#/$defs/relPath"
      },
      "sourceSha256": {
       "$ref": "common.schema.json#/$defs/sha256"
      },
      "startSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "endSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "type": {
       "enum": [
        "manual",
        "transient",
        "beat",
        "loop",
        "analysis-suggestion"
       ]
      },
      "fromCandidateId": {
       "$ref": "common.schema.json#/$defs/stableId"
      },
      "confidence": {
       "$ref": "common.schema.json#/$defs/confidence"
      },
      "createdBy": {
       "type": "string"
      },
      "createdAt": {
       "$ref": "common.schema.json#/$defs/isoTime"
      }
     },
     "required": [
      "id",
      "startSeconds",
      "endSeconds",
      "type"
     ],
     "additionalProperties": true
    }
   }
  },
  "required": [
   "schemaVersion",
   "chops"
  ],
  "additionalProperties": true
 },
 "common.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/common.schema.json",
  "title": "SP SYSTEM shared definitions",
  "$defs": {
   "uuid": {
    "type": "string",
    "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
   },
   "stableId": {
    "type": "string",
    "pattern": "^[a-z0-9][a-z0-9._-]{0,63}$",
    "description": "Stable, human-readable id, unique within its collection. Never reused after deletion."
   },
   "seconds": {
    "type": "number",
    "minimum": 0,
    "description": "Time on the source timeline in seconds (not samples)."
   },
   "confidence": {
    "type": [
     "number",
     "null"
    ],
    "minimum": 0,
    "maximum": 1,
    "description": "Producer's own estimate; null = not estimated. Not comparable across producers."
   },
   "sha256": {
    "type": "string",
    "pattern": "^[0-9a-f]{32,64}$",
    "description": "Lower-case hex of SHA-256 of the file bytes. 32 hex chars (LEARN's cache key) is accepted; compare by the shorter prefix."
   },
   "isoTime": {
    "type": "string",
    "format": "date-time"
   },
   "relPath": {
    "type": "string",
    "minLength": 1,
    "maxLength": 240,
    "pattern": "^(?!/)(?![A-Za-z]:)(?!.*(^|/)\\.\\.?(/|$))(?!.*\\\\)[^\\u0000-\\u001f]+$",
    "description": "Path inside the package: forward slashes, no leading slash, no drive letter, no '.' or '..' segments, no backslashes, no control characters."
   },
   "bank": {
    "type": "string",
    "pattern": "^[A-Z0-9]{1,4}$",
    "description": "Bank label. SP-404MKII banks are letters; the schema does not hard-code the count."
   },
   "pad": {
    "type": "integer",
    "minimum": 1,
    "maximum": 16,
    "description": "1..16, physical order of the SP-404MKII pad grid: 1 = bottom-left, 16 = top-right (as in LEARN's pad layout)."
   },
   "sampleCategory": {
    "enum": [
     "drum",
     "kick",
     "snare",
     "hat",
     "perc",
     "bass",
     "vocal",
     "melodic",
     "texture",
     "loop",
     "unknown"
    ]
   },
   "overridable": {
    "type": "object",
    "properties": {
     "raw": {
      "type": [
       "object",
       "null"
      ]
     },
     "userOverride": {
      "type": [
       "object",
       "null"
      ]
     }
    },
    "additionalProperties": true,
    "description": "Every inferred property: `raw` = what the engine said (never overwritten by a user); `userOverride` = what a person set. Readers use userOverride ?? raw."
   },
   "producer": {
    "type": "object",
    "properties": {
     "app": {
      "type": "string"
     },
     "version": {
      "type": "string"
     }
    },
    "required": [
     "app"
    ],
    "additionalProperties": true
   }
  }
 },
 "loops.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/loops.schema.json",
  "title": "Loops (project/loops.json)",
  "description": "Explicit loop regions.",
  "type": "object",
  "properties": {
   "schemaVersion": {
    "type": "integer",
    "minimum": 1
   },
   "loops": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "id": {
       "$ref": "common.schema.json#/$defs/stableId"
      },
      "name": {
       "type": "string"
      },
      "source": {
       "$ref": "common.schema.json#/$defs/relPath"
      },
      "startSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "endSeconds": {
       "$ref": "common.schema.json#/$defs/seconds"
      },
      "bars": {
       "type": "number",
       "exclusiveMinimum": 0
      },
      "bpm": {
       "type": "number",
       "exclusiveMinimum": 0
      },
      "confidence": {
       "$ref": "common.schema.json#/$defs/confidence"
      },
      "loopability": {
       "anyOf": [
        {
         "$ref": "common.schema.json#/$defs/confidence"
        }
       ],
       "description": "Future: how seamlessly the loop repeats (0..1). Optional."
      }
     },
     "required": [
      "id",
      "startSeconds",
      "endSeconds"
     ],
     "additionalProperties": true
    }
   }
  },
  "required": [
   "schemaVersion",
   "loops"
  ],
  "additionalProperties": true
 },
 "manifest.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/manifest.schema.json",
  "title": "SP SYSTEM manifest (manifest.json)",
  "description": "Required at the package root. Small, always parseable by every SP SYSTEM application; contains only what DROP can reliably produce.",
  "type": "object",
  "properties": {
   "format": {
    "const": "sp-system"
   },
   "formatVersion": {
    "type": "integer",
    "minimum": 1
   },
   "id": {
    "$ref": "common.schema.json#/$defs/uuid"
   },
   "createdBy": {
    "type": "string"
   },
   "createdByVersion": {
    "type": "string"
   },
   "createdAt": {
    "$ref": "common.schema.json#/$defs/isoTime"
   },
   "modifiedAt": {
    "$ref": "common.schema.json#/$defs/isoTime"
   },
   "modifiedBy": {
    "type": "string"
   },
   "modifiedByVersion": {
    "type": "string"
   },
   "revision": {
    "type": "integer",
    "minimum": 0,
    "description": "Incremented on every successful save by any application; used to detect that the package changed on disk since it was loaded."
   },
   "title": {
    "type": "string"
   },
   "source": {
    "type": "object",
    "properties": {
     "title": {
      "type": "string"
     },
     "originalFilename": {
      "type": "string"
     },
     "durationSeconds": {
      "type": "number",
      "minimum": 0
     },
     "sampleRate": {
      "type": "integer",
      "minimum": 1
     },
     "channels": {
      "type": "integer",
      "minimum": 1
     },
     "mode": {
      "enum": [
       "portable",
       "lightweight",
       "none"
      ],
      "description": "portable = audio/source.* inside the package; lightweight = referenced by externalSource; none = the project has samples only."
     },
     "audio": {
      "$ref": "common.schema.json#/$defs/relPath"
     },
     "sha256": {
      "$ref": "common.schema.json#/$defs/sha256"
     },
     "externalSource": {
      "type": "object",
      "properties": {
       "path": {
        "type": "string"
       },
       "hash": {
        "$ref": "common.schema.json#/$defs/sha256"
       },
       "sizeBytes": {
        "type": "integer",
        "minimum": 0
       },
       "lastSeenAt": {
        "$ref": "common.schema.json#/$defs/isoTime"
       }
      },
      "required": [
       "path",
       "hash"
      ]
     }
    },
    "additionalProperties": true
   },
   "tempo": {
    "type": "object",
    "description": "Working tempo (effective value). LEARN additionally keeps raw/userOverride in analysis/track.json.",
    "properties": {
     "bpm": {
      "type": "number",
      "exclusiveMinimum": 0
     },
     "confidence": {
      "$ref": "common.schema.json#/$defs/confidence"
     },
     "beatOffsetSeconds": {
      "type": "number"
     },
     "origin": {
      "enum": [
       "detected",
       "user",
       "imported"
      ]
     },
     "setBy": {
      "type": "string"
     },
     "setAt": {
      "$ref": "common.schema.json#/$defs/isoTime"
     }
    },
    "required": [
     "bpm"
    ],
    "additionalProperties": true
   },
   "meter": {
    "type": "object",
    "properties": {
     "beatsPerBar": {
      "type": "integer",
      "minimum": 1,
      "maximum": 32
     },
     "confidence": {
      "$ref": "common.schema.json#/$defs/confidence"
     }
    },
    "required": [
     "beatsPerBar"
    ],
    "additionalProperties": true
   },
   "modules": {
    "type": "object",
    "description": "Which optional parts the package contains and their own schema versions. Informational: readers must still look at the files.",
    "additionalProperties": {
     "type": "object",
     "properties": {
      "path": {
       "$ref": "common.schema.json#/$defs/relPath"
      },
      "schemaVersion": {
       "type": "integer",
       "minimum": 1
      },
      "owner": {
       "type": "string"
      },
      "sha256": {
       "$ref": "common.schema.json#/$defs/sha256"
      }
     },
     "additionalProperties": true
    }
   },
   "extensions": {
    "type": "object",
    "description": "Namespaced vendor data, e.g. {\"x-sp404-drop\": {...}}. Preserved by everyone."
   }
  },
  "required": [
   "format",
   "formatVersion",
   "id",
   "createdBy",
   "createdAt"
  ],
  "additionalProperties": true
 },
 "pads.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/pads.schema.json",
  "title": "Pad mapping (project/pads.json)",
  "description": "Flat list of assignments; any number of banks; empty pads may be omitted or have sampleId null.",
  "type": "object",
  "properties": {
   "schemaVersion": {
    "type": "integer",
    "minimum": 1
   },
   "assignments": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "bank": {
       "$ref": "common.schema.json#/$defs/bank"
      },
      "pad": {
       "$ref": "common.schema.json#/$defs/pad"
      },
      "sampleId": {
       "anyOf": [
        {
         "$ref": "common.schema.json#/$defs/stableId"
        },
        {
         "type": "null"
        }
       ]
      },
      "label": {
       "type": "string"
      }
     },
     "required": [
      "bank",
      "pad",
      "sampleId"
     ],
     "additionalProperties": true
    }
   }
  },
  "required": [
   "schemaVersion",
   "assignments"
  ],
  "additionalProperties": true
 },
 "progress.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/progress.schema.json",
  "title": "Lesson progress (learn/progress.json)",
  "description": "LEARN-owned; DROP ignores and preserves it.",
  "type": "object",
  "properties": {
   "progressVersion": {
    "type": "integer",
    "minimum": 1
   },
   "lessonsDone": {
    "type": "object",
    "additionalProperties": {
     "type": "number"
    },
    "description": "lesson id -> completion time (epoch ms)"
   },
   "practice": {
    "type": "object",
    "additionalProperties": {
     "type": "object"
    }
   }
  },
  "required": [
   "progressVersion"
  ],
  "additionalProperties": true
 },
 "recipe.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/recipe.schema.json",
  "title": "Educational recipe (learn/recipe.json)",
  "description": "LEARN-owned plan ('how could I build something like this / with this pack'). References library content by id; the library itself is not stored here.",
  "type": "object",
  "properties": {
   "recipeVersion": {
    "type": "integer",
    "minimum": 1
   },
   "kind": {
    "enum": [
     "track",
     "pack"
    ]
   },
   "title": {
    "type": "string"
   },
   "genre": {
    "type": [
     "string",
     "null"
    ]
   },
   "generatedFrom": {
    "type": "object",
    "properties": {
     "analysisVersion": {
      "type": "integer"
     },
     "packSampleCount": {
      "type": "integer"
     },
     "libraryVersion": {
      "type": "string"
     }
    },
    "additionalProperties": true
   },
   "steps": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "id": {
       "$ref": "common.schema.json#/$defs/stableId"
      },
      "title": {
       "type": "string"
      },
      "why": {
       "type": "string"
      },
      "items": {
       "type": "array",
       "items": {
        "type": "object",
        "properties": {
         "type": {
          "enum": [
           "lesson",
           "trick",
           "fx",
           "exercise",
           "reference"
          ]
         },
         "id": {
          "type": "string"
         }
        },
        "required": [
         "type",
         "id"
        ]
       }
      },
      "pads": {
       "type": "array",
       "items": {
        "type": "object",
        "properties": {
         "bank": {
          "$ref": "common.schema.json#/$defs/bank"
         },
         "pad": {
          "$ref": "common.schema.json#/$defs/pad"
         },
         "sampleId": {
          "$ref": "common.schema.json#/$defs/stableId"
         }
        },
        "required": [
         "bank",
         "pad"
        ]
       }
      }
     },
     "required": [
      "id",
      "title"
     ],
     "additionalProperties": true
    }
   }
  },
  "required": [
   "recipeVersion",
   "steps"
  ],
  "additionalProperties": true
 },
 "requirements.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/requirements.schema.json",
  "title": "Lesson requirements (learn/requirements.json)",
  "description": "LEARN-owned request to DROP: which kinds of samples a lesson needs. DROP shows progress by counting samples/chops by category; it never edits this file.",
  "type": "object",
  "properties": {
   "requirementsVersion": {
    "type": "integer",
    "minimum": 1
   },
   "lesson": {
    "type": "string"
   },
   "title": {
    "type": "string"
   },
   "needs": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "type": {
       "enum": [
        "drum-chop",
        "break-chop",
        "kick",
        "snare",
        "hat",
        "perc",
        "bass",
        "vocal-chop",
        "melodic",
        "texture",
        "loop",
        "any"
       ]
      },
      "count": {
       "type": "integer",
       "minimum": 1
      },
      "note": {
       "type": "string"
      }
     },
     "required": [
      "type",
      "count"
     ]
    }
   }
  },
  "required": [
   "requirementsVersion",
   "lesson",
   "needs"
  ],
  "additionalProperties": true
 },
 "samples.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sp-system/samples.schema.json",
  "title": "Sample records (project/samples.json)",
  "description": "Describes the audio files in samples/. Classification (category) is optional and never required.",
  "type": "object",
  "properties": {
   "schemaVersion": {
    "type": "integer",
    "minimum": 1
   },
   "samples": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "id": {
       "$ref": "common.schema.json#/$defs/stableId"
      },
      "file": {
       "$ref": "common.schema.json#/$defs/relPath"
      },
      "name": {
       "type": "string"
      },
      "sourceChopId": {
       "anyOf": [
        {
         "$ref": "common.schema.json#/$defs/stableId"
        },
        {
         "type": "null"
        }
       ]
      },
      "durationSeconds": {
       "type": "number",
       "minimum": 0
      },
      "sampleRate": {
       "type": "integer",
       "minimum": 1
      },
      "bitDepth": {
       "type": "integer",
       "enum": [
        8,
        16,
        24,
        32
       ]
      },
      "channels": {
       "type": "integer",
       "minimum": 1
      },
      "category": {
       "$ref": "common.schema.json#/$defs/sampleCategory"
      },
      "sha256": {
       "$ref": "common.schema.json#/$defs/sha256"
      }
     },
     "required": [
      "id",
      "file",
      "durationSeconds",
      "sampleRate",
      "bitDepth",
      "channels"
     ],
     "additionalProperties": true
    }
   }
  },
  "required": [
   "schemaVersion",
   "samples"
  ],
  "additionalProperties": true
 }
} };
});
